"""Fuse Suricata EVE alerts with Random Forest AI alerts.

This script is intentionally small and auditable for the thesis deployment
pipeline. It does not change the trained model. It correlates two alert streams:

- Suricata EVE JSON/JSONL alerts, usually from ``eve.json``.
- AI alerts generated by ``nids_detector.py`` in ``logs/ai_alerts.jsonl``.

The output is a JSONL file that can be ingested by Logstash/Kibana as the
Hybrid-NIDS alert stream.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable


SEVERITY_RANK = {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}
AI_CRITICAL_SCORE = 0.95
AI_HIGH_MARGIN = 0.10



@dataclass(frozen=True)
class NormalizedAlert:
    source: str
    timestamp: datetime
    raw: dict[str, Any]
    src_ip: str
    dst_ip: str
    dst_port: int
    protocol: str

    @property
    def key(self) -> tuple[str, str, int, str]:
        return (self.src_ip, self.dst_ip, self.dst_port, self.protocol)

    @property
    def host_key(self) -> tuple[str, str, str]:
        return (self.src_ip, self.dst_ip, self.protocol)


@dataclass(frozen=True)
class LabAttackWindow:
    scenario: str
    src_ip: str
    dst_ip: str
    proto: str
    port_ranges: tuple[tuple[int, int], ...]
    start: datetime | None
    end: datetime | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Dung hợp cảnh báo Suricata EVE và AI Random Forest thành hybrid_alerts.jsonl."
    )
    parser.add_argument("--suricata-eve", required=True, help="Đường dẫn eve.json/eve.jsonl của Suricata.")
    parser.add_argument("--ai-alerts", default="logs/ai_alerts.jsonl", help="Cảnh báo AI JSONL từ nids_detector.py.")
    parser.add_argument("--output", default="logs/hybrid_alerts.jsonl", help="File JSONL đầu ra sau dung hợp.")
    parser.add_argument(
        "--window-seconds",
        type=int,
        default=300,
        help="Cửa sổ thời gian để xem hai cảnh báo là cùng sự kiện.",
    )
    parser.add_argument(
        "--include-unmatched",
        action="store_true",
        help="Ghi cả AI_ONLY_ALERT và SURICATA_ONLY_ALERT. Mặc định chỉ ghi hybrid correlated alerts.",
    )
    parser.add_argument(
        "--max-records",
        type=int,
        default=0,
        help="Giới hạn số dòng đọc mỗi nguồn để tạo mẫu nhanh. 0 nghĩa là đọc toàn bộ.",
    )
    parser.add_argument(
        "--correlation-key",
        choices=("strict", "host_pair"),
        default="strict",
        help="strict: khớp cả cổng; host_pair: khớp IP/protocol, chỉ dùng cho kiểm chứng lab.",
    )
    parser.add_argument(
        "--enable-hybrid-plus-demo",
        action="store_true",
        help="Bật Hybrid+ Demo dựa trên Suricata và ground truth lab. Không dùng trong vận hành thật.",
    )
    parser.add_argument(
        "--demo-ground-truth-csv",
        type=Path,
        help="attack_windows.csv của phiên lab; bắt buộc khi bật Hybrid+ Demo.",
    )
    parser.add_argument(
        "--append-unique",
        action="store_true",
        help="Nối cảnh báo mới vào output và chống trùng bằng event_id.",
    )
    parser.add_argument(
        "--archive-output",
        type=Path,
        help="Đồng thời nối cảnh báo mới vào file lịch sử có chống trùng.",
    )
    parser.add_argument(
        "--require-time-overlap",
        action="store_true",
        help=(
            "Dừng nếu khoảng thời gian Suricata và AI không giao nhau trong "
            "cửa sổ tương quan. Dùng cho đánh giá lab để tránh sinh metric sai."
        ),
    )
    return parser.parse_args()


def parse_timestamp(value: Any) -> datetime:
    if not value:
        return datetime.now(timezone.utc)

    text = str(value).strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"

    # Suricata sometimes emits timestamps such as 2026-06-27T16:03:07.422362+0700.
    if len(text) >= 5 and (text[-5] in ["+", "-"]) and text[-3] != ":":
        text = f"{text[:-2]}:{text[-2:]}"

    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        # Keep the fusion pipeline resilient; invalid timestamps should not drop alerts.
        return datetime.now(timezone.utc)

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def safe_int(value: Any, default: int = 0) -> int:
    try:
        if value in (None, ""):
            return default
        return int(float(value))
    except (TypeError, ValueError):
        return default


def safe_float(value: Any) -> float | None:
    try:
        if value in (None, ""):
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def normalize_severity(value: Any) -> str:
    text = str(value or "LOW").strip().upper()
    return text if text in SEVERITY_RANK else "LOW"


def normalize_protocol(value: Any) -> str:
    text = str(value or "-").strip().lower()
    aliases = {"6": "tcp", "17": "udp", "1": "icmp"}
    return aliases.get(text, text)


def _first(row: dict[str, str], *keys: str) -> str:
    for key in keys:
        value = row.get(key, "")
        if value not in ("", None):
            return str(value).strip()
    return ""


def _parse_port_ranges(value: str) -> tuple[tuple[int, int], ...]:
    text = (value or "").strip().lower()
    if text in ("", "*", "any"):
        return ((0, 65535),)
    ranges: list[tuple[int, int]] = []
    for token in re.split(r"[;| ]+", text):
        if not token:
            continue
        if "-" in token:
            left, right = token.split("-", 1)
            ranges.append((safe_int(left, 0), safe_int(right, 65535)))
        else:
            port = safe_int(token, -1)
            if 0 <= port <= 65535:
                ranges.append((port, port))
    return tuple(ranges or [(0, 65535)])


def load_lab_attack_windows(path: Path) -> list[LabAttackWindow]:
    windows: list[LabAttackWindow] = []
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        for raw in reader:
            row = {(key or "").strip().lower(): (value or "").strip() for key, value in raw.items()}
            label = _first(row, "label").lower()
            if label not in ("1", "attack", "malicious", "true"):
                continue
            start_text = _first(row, "start_utc", "start", "started_at")
            end_text = _first(row, "end_utc", "end", "ended_at")
            windows.append(
                LabAttackWindow(
                    scenario=_first(row, "scenario", "attack_type") or "LAB_ATTACK",
                    src_ip=_first(row, "attacker_ip", "srcip", "src_ip"),
                    dst_ip=_first(row, "target_ip", "dstip", "dst_ip"),
                    proto=normalize_protocol(_first(row, "proto", "protocol")),
                    port_ranges=_parse_port_ranges(_first(row, "dst_port", "dsport")),
                    start=parse_timestamp(start_text) if start_text else None,
                    end=parse_timestamp(end_text) if end_text else None,
                )
            )
    return windows


def matching_lab_window(
    alert: NormalizedAlert,
    windows: list[LabAttackWindow],
    tolerance_seconds: int = 5,
) -> LabAttackWindow | None:
    tolerance = timedelta(seconds=max(0, tolerance_seconds))
    for window in windows:
        if not window.src_ip or not window.dst_ip:
            continue
        if alert.src_ip != window.src_ip or alert.dst_ip != window.dst_ip:
            continue
        if window.proto not in ("", "-", "*", "any") and alert.protocol != window.proto:
            continue
        if not any(low <= alert.dst_port <= high for low, high in window.port_ranges):
            continue
        if window.start and alert.timestamp < window.start - tolerance:
            continue
        if window.end and alert.timestamp > window.end + tolerance:
            continue
        return window
    return None


def read_json_lines(path: Path, max_records: int = 0) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as file:
        count = 0
        for line_no, line in enumerate(file, 1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                record = json.loads(stripped)
            except json.JSONDecodeError:
                # Bo qua dong JSON hong (vd Suricata dang ghi do) thay vi crash toan bo.
                continue
            yield record
            count += 1
            if max_records and count >= max_records:
                break


def normalize_ai_alert(record: dict[str, Any]) -> NormalizedAlert | None:
    if not record.get("src_ip") or not record.get("dst_ip"):
        return None
    return NormalizedAlert(
        source="ai",
        timestamp=parse_timestamp(record.get("timestamp_utc") or record.get("@timestamp")),
        raw=record,
        src_ip=str(record.get("src_ip", "")),
        dst_ip=str(record.get("dst_ip", "")),
        dst_port=safe_int(record.get("dst_port")),
        protocol=normalize_protocol(record.get("protocol")),
    )


def normalize_suricata_alert(record: dict[str, Any]) -> NormalizedAlert | None:
    if record.get("event_type") and record.get("event_type") != "alert":
        return None
    if not record.get("src_ip") or not (record.get("dest_ip") or record.get("dst_ip")):
        return None
    return NormalizedAlert(
        source="suricata",
        timestamp=parse_timestamp(record.get("timestamp") or record.get("timestamp_utc") or record.get("@timestamp")),
        raw=record,
        src_ip=str(record.get("src_ip", "")),
        dst_ip=str(record.get("dest_ip") or record.get("dst_ip") or ""),
        dst_port=safe_int(record.get("dest_port", record.get("dst_port"))),
        protocol=normalize_protocol(record.get("proto") or record.get("protocol")),
    )


def severity_from_suricata(record: dict[str, Any]) -> str:
    alert = record.get("alert") if isinstance(record.get("alert"), dict) else {}
    severity = safe_int(alert.get("severity"), default=3)
    if severity <= 1:
        return "CRITICAL"
    if severity == 2:
        return "HIGH"
    if severity == 3:
        return "MEDIUM"
    return "LOW"


def max_severity(*values: str) -> str:
    normalized = [normalize_severity(value) for value in values]
    return max((value or "LOW" for value in normalized), key=lambda value: SEVERITY_RANK.get(value, 0))


def severity_from_ai(record: dict[str, Any]) -> tuple[str, str]:
    declared = normalize_severity(record.get("severity"))
    score = safe_float(record.get("attack_score"))
    threshold = safe_float(record.get("threshold"))

    score_severity = "LOW"
    reason = "AI severity from declared value only"
    if score is not None:
        if score >= AI_CRITICAL_SCORE:
            score_severity = "CRITICAL"
            reason = f"attack_score={score:.4f} >= {AI_CRITICAL_SCORE:.2f}"
        elif threshold is not None and score >= threshold + AI_HIGH_MARGIN:
            score_severity = "HIGH"
            reason = f"attack_score={score:.4f} >= threshold+{AI_HIGH_MARGIN:.2f}"
        elif threshold is not None and score >= threshold:
            score_severity = "MEDIUM"
            reason = f"attack_score={score:.4f} >= threshold"
        else:
            reason = "attack_score below threshold or threshold unavailable"

    return max_severity(declared, score_severity), reason


def fused_severity(
    action: str,
    ai_raw: dict[str, Any],
    suri_raw: dict[str, Any],
) -> tuple[str, str, str, str]:
    ai_severity, ai_reason = severity_from_ai(ai_raw) if ai_raw else ("LOW", "AI branch absent")
    suri_severity = severity_from_suricata(suri_raw) if suri_raw else "LOW"
    base = max_severity(ai_severity, suri_severity)

    if action == "HYBRID_PLUS_DEMO_ALERT":
        severity = max_severity(base, "HIGH")
        return severity, ai_severity, suri_severity, (
            "controlled-lab corroboration: Suricata matched a labelled attack window; "
            "Random Forest did not independently confirm this event"
        )

    if action != "HYBRID_CORRELATED_ALERT":
        return base, ai_severity, suri_severity, f"single-branch severity={base}; {ai_reason}"

    if base in {"HIGH", "CRITICAL"}:
        return "CRITICAL", ai_severity, suri_severity, (
            "correlated alert escalated because at least one branch is HIGH/CRITICAL; "
            f"ai={ai_severity}, suricata={suri_severity}; {ai_reason}"
        )

    return "HIGH", ai_severity, suri_severity, (
        "correlated alert raised to HIGH, not auto-CRITICAL, because both branches match "
        f"but neither branch is HIGH/CRITICAL; ai={ai_severity}, suricata={suri_severity}; {ai_reason}"
    )


def make_hybrid_record(
    *,
    action: str,
    ai: NormalizedAlert | None,
    suricata: NormalizedAlert | None,
    window_seconds: int,
    lab_window: LabAttackWindow | None = None,
) -> dict[str, Any]:
    primary = ai or suricata
    assert primary is not None

    ai_raw = ai.raw if ai else {}
    suri_raw = suricata.raw if suricata else {}
    suri_alert = suri_raw.get("alert") if isinstance(suri_raw.get("alert"), dict) else {}

    severity, ai_severity, suri_severity, correlation_reason = fused_severity(action, ai_raw, suri_raw)

    timestamp = max(
        [item.timestamp for item in [ai, suricata] if item is not None],
        default=datetime.now(timezone.utc),
    )

    record = {
        "timestamp_utc": timestamp.isoformat(),
        "event_dataset": (
            "hybrid_nids.lab_demo_alert"
            if action == "HYBRID_PLUS_DEMO_ALERT"
            else "hybrid_nids.hybrid_alert"
        ),
        "alert_source": "hybrid_fusion",
        "action": action,
        "severity": severity,
        "correlation_reason": correlation_reason,
        "correlation_window_seconds": window_seconds,
        "src_ip": primary.src_ip,
        "dst_ip": primary.dst_ip,
        "dst_port": primary.dst_port,
        "protocol": primary.protocol,
        "sources": [
            source
            for source, item in [
                ("suricata", suricata),
                ("random_forest_ai", ai),
                ("lab_ground_truth", lab_window),
            ]
            if item is not None
        ],
        "ai": {
            "present": ai is not None,
            "attack_score": ai_raw.get("attack_score"),
            "threshold": ai_raw.get("threshold"),
            "application_name": ai_raw.get("application_name"),
            "normalized_severity": ai_severity,
        },
        "suricata": {
            "present": suricata is not None,
            "signature": suri_alert.get("signature"),
            "signature_id": suri_alert.get("signature_id"),
            "category": suri_alert.get("category"),
            "severity": suri_alert.get("severity"),
            "normalized_severity": suri_severity,
        },
        "lab_demo": {
            "enabled": lab_window is not None,
            "scenario": lab_window.scenario if lab_window else None,
            "evidence": "suricata_plus_labelled_attack_window" if lab_window else None,
            "rf_confirmed": ai is not None,
            "scope": "controlled_lab_only" if lab_window else None,
        },
        "recommendation": recommendation_for(action),
    }
    identity = {
        "action": action,
        "timestamp_utc": record["timestamp_utc"],
        "src_ip": record["src_ip"],
        "dst_ip": record["dst_ip"],
        "dst_port": record["dst_port"],
        "protocol": record["protocol"],
        "signature_id": record["suricata"]["signature_id"],
        "attack_score": record["ai"]["attack_score"],
        "scenario": record["lab_demo"]["scenario"],
    }
    record["event_id"] = hashlib.sha256(
        json.dumps(identity, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:24]
    return record


def recommendation_for(action: str) -> str:
    if action == "HYBRID_CORRELATED_ALERT":
        return "Ưu tiên rà soát: hai nhánh cùng ghi nhận trong cửa sổ tương quan; mức ưu tiên phụ thuộc severity và attack_score."
    if action == "AI_ONLY_ALERT":
        return "Đối chiếu thêm Suricata/firewall log; có thể là hành vi bất thường chưa khớp rule."
    if action == "HYBRID_PLUS_DEMO_ALERT":
        return (
            "Bằng chứng kiểm chứng lab: Suricata khớp cửa sổ tấn công đã gán nhãn. "
            "Không diễn giải là Random Forest đã phát hiện hoặc là metric vận hành chính thức."
        )
    return "Đối chiếu attack_score của AI và kiểm tra rule SID để xác minh mức độ ưu tiên."


def correlate_alerts(
    suricata_alerts: list[NormalizedAlert],
    ai_alerts: list[NormalizedAlert],
    *,
    window_seconds: int,
    include_unmatched: bool,
    correlation_key: str = "strict",
    demo_windows: list[LabAttackWindow] | None = None,
) -> list[dict[str, Any]]:
    def key_for(alert: NormalizedAlert) -> tuple[Any, ...]:
        return alert.host_key if correlation_key == "host_pair" else alert.key

    ai_by_key: dict[tuple[Any, ...], list[tuple[int, NormalizedAlert]]] = {}
    for idx, alert in enumerate(ai_alerts):
        ai_by_key.setdefault(key_for(alert), []).append((idx, alert))
    for alerts in ai_by_key.values():
        alerts.sort(key=lambda item: item[1].timestamp)

    used_ai: set[int] = set()
    results: list[dict[str, Any]] = []

    suricata_by_key: dict[tuple[Any, ...], list[NormalizedAlert]] = {}
    for alert in suricata_alerts:
        suricata_by_key.setdefault(key_for(alert), []).append(alert)

    window = timedelta(seconds=max(0, window_seconds))
    for key, keyed_suricata in suricata_by_key.items():
        keyed_suricata.sort(key=lambda alert: alert.timestamp)
        keyed_ai = ai_by_key.get(key, [])
        ai_cursor = 0

        for suricata in keyed_suricata:
            lower_bound = suricata.timestamp - window
            upper_bound = suricata.timestamp + window

            # AI cũ hơn lower_bound không thể khớp với cảnh báo Suricata hiện
            # tại hoặc bất kỳ cảnh báo Suricata nào đến sau.
            while (
                ai_cursor < len(keyed_ai)
                and keyed_ai[ai_cursor][1].timestamp < lower_bound
            ):
                ai_cursor += 1

            matched: tuple[int, NormalizedAlert] | None = None
            if (
                ai_cursor < len(keyed_ai)
                and keyed_ai[ai_cursor][1].timestamp <= upper_bound
            ):
                matched = keyed_ai[ai_cursor]
                ai_cursor += 1

            if matched is not None:
                used_ai.add(matched[0])
                results.append(
                    make_hybrid_record(
                        action="HYBRID_CORRELATED_ALERT",
                        ai=matched[1],
                        suricata=suricata,
                        window_seconds=window_seconds,
                    )
                )
                continue

            lab_window = matching_lab_window(suricata, demo_windows or [])
            if lab_window is not None:
                results.append(
                    make_hybrid_record(
                        action="HYBRID_PLUS_DEMO_ALERT",
                        ai=None,
                        suricata=suricata,
                        window_seconds=window_seconds,
                        lab_window=lab_window,
                    )
                )
            elif include_unmatched:
                results.append(
                    make_hybrid_record(
                        action="SURICATA_ONLY_ALERT",
                        ai=None,
                        suricata=suricata,
                        window_seconds=window_seconds,
                    )
                )

    if include_unmatched:
        for idx, ai in enumerate(ai_alerts):
            if idx not in used_ai:
                results.append(
                    make_hybrid_record(
                        action="AI_ONLY_ALERT",
                        ai=ai,
                        suricata=None,
                        window_seconds=window_seconds,
                    )
                )

    return sorted(results, key=lambda record: record["timestamp_utc"])


def print_correlation_diagnostics(
    suricata_alerts: list[NormalizedAlert],
    ai_alerts: list[NormalizedAlert],
    correlation_key: str,
    window_seconds: int,
) -> bool:
    def key_for(alert: NormalizedAlert) -> tuple[Any, ...]:
        return alert.host_key if correlation_key == "host_pair" else alert.key

    suri_keys = {key_for(alert) for alert in suricata_alerts}
    ai_keys = {key_for(alert) for alert in ai_alerts}
    shared_keys = suri_keys & ai_keys
    print(f"[i] Correlation keys: Suricata={len(suri_keys)}, AI={len(ai_keys)}, shared={len(shared_keys)}")
    if suricata_alerts:
        print(
            "[i] Suricata time range: "
            f"{min(a.timestamp for a in suricata_alerts).isoformat()} -> "
            f"{max(a.timestamp for a in suricata_alerts).isoformat()}"
        )
    if ai_alerts:
        print(
            "[i] AI time range: "
            f"{min(a.timestamp for a in ai_alerts).isoformat()} -> "
            f"{max(a.timestamp for a in ai_alerts).isoformat()}"
        )
    if not suricata_alerts or not ai_alerts:
        return False
    tolerance = timedelta(seconds=max(0, window_seconds))
    suri_start = min(a.timestamp for a in suricata_alerts)
    suri_end = max(a.timestamp for a in suricata_alerts)
    ai_start = min(a.timestamp for a in ai_alerts)
    ai_end = max(a.timestamp for a in ai_alerts)
    overlaps = suri_start <= ai_end + tolerance and ai_start <= suri_end + tolerance
    print(f"[i] Time ranges overlap within {window_seconds}s: {str(overlaps).lower()}")
    return overlaps


def write_jsonl(
    path: Path,
    records: Iterable[dict[str, Any]],
    *,
    append_unique: bool = False,
) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing_ids: set[str] = set()
    if append_unique and path.exists():
        for record in read_json_lines(path):
            event_id = str(record.get("event_id") or "")
            if event_id:
                existing_ids.add(event_id)
    count = 0
    mode = "a" if append_unique else "w"
    with path.open(mode, encoding="utf-8") as file:
        for record in records:
            event_id = str(record.get("event_id") or "")
            if append_unique and event_id and event_id in existing_ids:
                continue
            file.write(json.dumps(record, ensure_ascii=False) + "\n")
            if event_id:
                existing_ids.add(event_id)
            count += 1
    return count


def main() -> None:
    args = parse_args()
    suricata_path = Path(args.suricata_eve)
    ai_path = Path(args.ai_alerts)
    output_path = Path(args.output)

    if not suricata_path.exists():
        raise FileNotFoundError(f"Suricata EVE file not found: {suricata_path}")
    if not ai_path.exists():
        raise FileNotFoundError(f"AI alert file not found: {ai_path}")
    if args.enable_hybrid_plus_demo and not args.demo_ground_truth_csv:
        raise ValueError("--demo-ground-truth-csv is required with --enable-hybrid-plus-demo")
    if args.demo_ground_truth_csv and not args.demo_ground_truth_csv.exists():
        raise FileNotFoundError(f"Lab ground-truth file not found: {args.demo_ground_truth_csv}")

    suricata_alerts = [
        alert
        for record in read_json_lines(suricata_path, args.max_records)
        if (alert := normalize_suricata_alert(record)) is not None
    ]
    ai_alerts = [
        alert
        for record in read_json_lines(ai_path, args.max_records)
        if (alert := normalize_ai_alert(record)) is not None
    ]

    demo_windows = (
        load_lab_attack_windows(args.demo_ground_truth_csv)
        if args.enable_hybrid_plus_demo and args.demo_ground_truth_csv
        else []
    )
    time_ranges_overlap = print_correlation_diagnostics(
        suricata_alerts,
        ai_alerts,
        args.correlation_key,
        args.window_seconds,
    )
    if args.require_time_overlap and not time_ranges_overlap:
        raise SystemExit(
            "[X] Suricata va AI khong cung khoang thoi gian. "
            "Khong sinh bang metric; kiem tra timestamp_source/start_utc."
        )
    fused = correlate_alerts(
        suricata_alerts,
        ai_alerts,
        window_seconds=args.window_seconds,
        include_unmatched=args.include_unmatched,
        correlation_key=args.correlation_key,
        demo_windows=demo_windows,
    )
    written = write_jsonl(output_path, fused, append_unique=args.append_unique)
    archived = 0
    if args.archive_output and args.archive_output.resolve() != output_path.resolve():
        archived = write_jsonl(args.archive_output, fused, append_unique=True)

    correlated = sum(1 for record in fused if record["action"] == "HYBRID_CORRELATED_ALERT")
    hybrid_plus = sum(1 for record in fused if record["action"] == "HYBRID_PLUS_DEMO_ALERT")
    ai_only = sum(1 for record in fused if record["action"] == "AI_ONLY_ALERT")
    suricata_only = sum(1 for record in fused if record["action"] == "SURICATA_ONLY_ALERT")

    print(f"[+] Suricata alerts: {len(suricata_alerts)}")
    print(f"[+] AI alerts: {len(ai_alerts)}")
    print(f"[+] Hybrid correlated: {correlated}")
    print(f"[+] Hybrid+ Demo (Suricata + labelled ground truth): {hybrid_plus}")
    print(f"[+] AI only: {ai_only}")
    print(f"[+] Suricata only: {suricata_only}")
    print(f"[+] Wrote {written} fused alerts to {output_path}")
    if args.archive_output:
        print(f"[+] Archived {archived} new alerts to {args.archive_output}")


if __name__ == "__main__":
    main()
